name: OFRP CI

on:
  workflow_dispatch:

jobs:
  build:
    name: OFRP Build CI
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Installing build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc schedtool
          sudo ln -f -s /usr/bin/python2.7 /usr/bin/python

      - name: Syncing OFRP sources
        run: |
          mkdir ~/OFRP
          cd ~/OFRP

          mkdir ~/.bin
          curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          python3 ~/.bin/repo init --depth=1 -u https://github.com/OrangeFoxRecovery/fox-6.0_manifest.git -b fox_6.0
          python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
          git clone --branch twrp-6.0 --single-branch https://github.com/TriDiscord/android_device_casper_viam1.git ~/OFRP/device/casper/viam1
          chmod -R a+x device/casper/viam1

      - name: Building OFRP
        run: |
          cd ~/OFRP
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export OF_DISABLE_KEYMASTER2=1
          export LC_ALL=C
          lunch omni_viam1-eng
          make -j$(nproc --all) recoveryimage

      - name: Uploading OFRP builds
        uses: actions/upload-artifact@v2
        with:
          name: OFRP
          path: /home/runner/OFRP/out/target/product/viam1/recovery.*
