name: Recovery CI

on:
  workflow_dispatch:

jobs:
  twrp:
    name: TWRP Builder
    runs-on: ubuntu-18.04

    steps:
      - name: Installing build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc schedtool
          sudo ln -f -s /usr/bin/python2.7 /usr/bin/python

      - name: Syncing TWRP sources
        run: |
          mkdir ~/TWRP
          cd ~/TWRP

          mkdir ~/.bin
          sudo curl http://commondatastorage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/zero
          sudo chmod 777 /usr/bin/repo
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
          git clone --depth=1 --branch omni-9.0 --single-branch https://github.com/viam1-dev/android_device_casper_viam1.git ~/TWRP/device/casper/viam1

      - name: Building TWRP
        run: |
          cd ~/TWRP
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export LC_ALL=C
          lunch omni_viam1-eng
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
          mka recoveryimage

      - name: Uploading TWRP builds
        uses: actions/upload-artifact@v2
        with:
          name: TWRP_viam1
          path: /home/runner/TWRP/out/target/product/viam1/recovery.img
  
  ofrp:
    name: OFRP Builder
    runs-on: ubuntu-18.04

    steps:
      - name: Installing build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc schedtool
          sudo ln -f -s /usr/bin/python2.7 /usr/bin/python

      - name: Syncing OFRP sources
        run: |
          mkdir ~/OFRP
          cd ~/OFRP

          mkdir ~/.bin
          sudo curl http://commondatastorage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/zero
          sudo chmod 777 /usr/bin/repo
          repo init --depth=1 -u https://gitlab.com/OrangeFox/Manifest.git -b fox_7.1
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
          git clone --depth=1 --branch master --single-branch https://gitlab.com/OrangeFox/misc/theme.git ~/OFRP/bootable/recovery/gui/theme
          git clone --depth=1 --branch omni-9.0 --single-branch https://github.com/viam1-dev/android_device_casper_viam1.git ~/OFRP/device/casper/viam1
          chmod -R a+x device/casper/viam1

      - name: Building OFRP
        run: |
          cd ~/OFRP
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export LC_ALL=C
          lunch omni_viam1-eng
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
          make -j$(nproc --all) recoveryimage

      - name: Uploading OFRP builds
        uses: actions/upload-artifact@v2
        with:
          name: OFRP_viam1
          path: /home/runner/OFRP/out/target/product/viam1/recovery.img
